# Generated by Django 4.1.2 on 2022-10-12 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품이름')),
                ('price', models.PositiveIntegerField(verbose_name='상품 정가')),
                ('sale_price', models.PositiveIntegerField(verbose_name='상품 할인가')),
                ('stock', models.BooleanField(default=True, verbose_name='제고유무')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='상품 담당자')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='상품 태그')),
                ('tagid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttags', to='product.product')),
            ],
        ),
    ]
